//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MecnunDergi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uye()
        {
            this.Yorum = new HashSet<Yorum>();
            this.Makale = new HashSet<Makale>();
        }
    
        public int UyeId { get; set; }
        [Required]
        [StringLength(50)]
        public string AdSoyad { get; set; }
        [Required]
        [StringLength(50)]
        public string KullanıcıAdı { get; set; }
        [Required]
        [StringLength(250)]
        [DataType(DataType.EmailAddress)]
        [Display(Name ="Eposta Ardesi")]
        public string Email { get; set; }
        [Required]
        [StringLength(20)]
        [MaxLength(20)]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
        [Required]
        [Display(Name ="Profil Fotoğrafı")]
        public string Foto { get; set; }
        [Display(Name ="Yetkisi")]
        public Nullable<int> YetkiId { get; set; }
    
        public virtual Yetki Yetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makale> Makale { get; set; }
    }
}
